version: "3"

services:
  reverse-proxy:
    image: traefik:v2.3
    command:
      - --providers.docker
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - back
      - front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik/:ro
      - ./cert/:/cert/

  redirect-main:
    image: registry.gitlab.com/zombuild/docker-redirect
    environment:
      - "REDIRECT_URL=https://ubirch.com"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redirect-main.rule=Host(`ubirch.world`) && Path(`/{firstlevel:[a-zA-Z0-9-_]*}`)"
      - "traefik.http.routers.redirect-main.priority=1000"
      - "traefik.http.routers.redirect-main.tls=true"
      - "traefik.http.routers.redirect-main.tls.domains[0].main=ubirch.world"
      - "traefik.http.routers.redirect-main.tls.certresolver=default"

  redirect-office:
    image: registry.gitlab.com/zombuild/docker-redirect
    environment:
      - "REDIRECT_URL=https://ubirch.world/_/global/raw.githubusercontent.com/ubirch/workadventure_map/master/map.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redirect-office.rule=Host(`ubirch.world`) && Path(`/office`)"
      - "traefik.http.routers.redirect-office.priority=2000"
      - "traefik.http.routers.redirect-office.tls=true"
      - "traefik.http.routers.redirect-office.tls.domains[0].main=ubirch.world"
      - "traefik.http.routers.redirect-office.tls.certresolver=default"

  front:
    image: thecodingmachine/nodejs:14
    environment:
      DEBUG_MODE: "$DEBUG_MODE"
      JITSI_URL: "meet.ffmuc.net"
      JITSI_PRIVATE_MODE: "$JITSI_PRIVATE_MODE"
      HOST: "0.0.0.0"
      NODE_ENV: development
      API_URL: api.ubirch.world
      ADMIN_URL: admin.workadventure.localhost
      STARTUP_COMMAND_1: yarn install
      TURN_SERVER: "turn:coturn.workadventu.re:443,turns:coturn.workadventu.re:443"
      TURN_USER: workadventure
      TURN_PASSWORD: WorkAdventure123
    command: yarn run start
    restart: on-failure
    volumes:
      - ./front:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`ubirch.world`)"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.domains[0].main=ubirch.world"
      - "traefik.http.routers.front.tls.certresolver=default"
      - "traefik.http.middlewares.static-password.basicauth.users=cyber:$$apr1$$6tb1v72w$$ka6/d71wy.YI7s9dKJeY50"
      - "traefik.http.routers.front.middlewares=static-password"


  back:
    image: thecodingmachine/nodejs:12
    command: yarn dev
    restart: on-failure
    environment:
      STARTUP_COMMAND_1: yarn install
      SECRET_KEY: yourSecretKey
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      ALLOW_ARTILLERY: "true"
      ADMIN_API_TOKEN: "OpelCalibra"
      JITSI_URL: "meet.ffmuc.net"
      JITSI_ISS: $JITSI_ISS
    volumes:
      - ./back:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.back.rule=Host(`api.ubirch.world`)"
      - "traefik.http.routers.back.tls=true"
      - "traefik.http.routers.back.tls.domains[0].main=api.ubirch.world"
      - "traefik.http.routers.back.tls.certresolver=default"
      - "traefik.http.services.back.loadbalancer.server.port=8080"

# messages:
#   image: thecodingmachine/workadventure-back-base:latest
#   environment:
#     STARTUP_COMMAND_1: yarn install
#     STARTUP_COMMAND_2: yarn run proto:watch
#   volumes:
#     - ./messages:/usr/src/app
#     - ./back:/usr/src/back
#     - ./front:/usr/src/front
